version: '3.1'

services:

  db:
    image: postgres
    container_name: store_seller_db
    restart: always 
    environment:
        - POSTGRES_USER=store
        - POSTGRES_PASSWORD=store
        - POSTGRES_DB=store
    ports: 
        - 5342:5432


  web:
    build: .
    container_name: store_seller_app
    command: ["sh", "./this.sh"]
    volumes:
        - .:/code
    depends_on:
        - db
    links:
        - db
    ports: 
        - "8000:8000"

    restart: always
